{{ if (eq .env "dev") }}
---
image: wfs
from: node:22
git:
- add: /prepare-scripts
  to: /install/prepare-scripts
docker:
  WORKDIR: /workspace/
  USER: root
  EXPOSE: "80"

ansible:
  install:
  - name: "Install additional packages"
    apt:
      state: present
      update_cache: yes
      pkg:
      - locales
      - mc
      - vim
      - neovim
      - telnet
  - name: "Install packages"
    block:
    - name: "Install @nestjs/cli"
      npm:
        name: "@nestjs/cli"
        global: yes
        state: present
    - name: "Install pnpm"
      npm:
        name: "pnpm"
        global: yes
        state: present
  - name: "Configure SSH"
    lineinfile:
      path: /etc/ssh/ssh_config
      line: "Host github.com\n\tStrictHostKeyChecking no\n\tUserKnownHostsFile=/dev/null"
---
image: wfs-api
fromImage: wfs
docker:
  CMD: ["/bin/sleep", "infinity"]
  WORKDIR: /workspace
---
image: wfs-cron
fromImage: wfs
docker:
  CMD: ["/bin/sleep", "infinity"]
  WORKDIR: /workspace
---
image: wfs-discord
fromImage: wfs
docker:
  CMD: ["/bin/sleep", "infinity"]
  WORKDIR: /workspace
---
image: wfs-vk
fromImage: wfs
docker:
  CMD: ["/bin/sleep", "infinity"]
  WORKDIR: /workspace
---
image: wfs-telegram
fromImage: wfs
docker:
  CMD: ["/bin/sleep", "infinity"]
  WORKDIR: /workspace
---
image: wfs-front
fromImage: wfs
docker:
  CMD: ["/bin/sleep", "infinity"]
  WORKDIR: /workspace
---
{{ end }}
