export enum MissionEnum {
  Sunrise = 'sunrise',
  Pripyat = 'pripyat',
  Coldpeak = 'coldpeak',
  Mars = 'mars',
  Blackout = 'blackout',
  Anubis = 'anubis',
  EarthShaker = 'earth_shaker',
  CyberHorde = 'cyber_horde',
  Icebreaker = 'icebreaker',
  TheHQ = 'the_hq',
  BlackShark = 'black_shark',
  Swarm = 'swarm',
  Hydra = 'hydra',
  Blackwood = 'blackwood',
  Heist = 'heist',
  Endor = 'endorsurvival',
  Midgard = 'midgard',
}
