apiVersion: v1
kind: ConfigMap
metadata:
  name: wg-config
data:
  wg-pre-up.sh: |
{{ .Values.wireguardPreUpScript | indent 4 }}
  wg-post-up.sh: |
{{ .Values.wireguardPostUpScript | indent 4 }}
  wg-api.conf: |
{{ .Values.wireguardConfig | indent 4 }}
  wg-discord.conf: |
{{ .Values.wireguardDiscordConfig | indent 4 }}