{{ $replicaCount := index .Values "apiReplicaCount" }}
{{ if  (ne .Values.werf.env "dev") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-api
  labels:
    app: {{ .Chart.Name }}-api
spec:
  replicas: {{ $replicaCount }}
  selector:
      matchLabels:
        app: {{ .Chart.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-api
    spec:
      containers:
      - name: {{ .Chart.Name }}-api
        image: '{{ index .Values.werf.image "wfs-api" }}'
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config
      - name: wg-client
        image: globalartltd/wireguard:rc3
        securityContext:
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Moscow"
        volumeMounts:
        - name: wg-config
          mountPath: /etc/wireguard/wg0.conf
          subPath: wg-api.conf
        - name: wg-config
          mountPath: /etc/wireguard/pre-up.sh
          subPath: wg-pre-up.sh
        - name: wg-config
          mountPath: /etc/wireguard/post-up.sh
          subPath: wg-post-up.sh
        - name: wg-config
          mountPath: /etc/wireguard/post-down.sh
          subPath: wg-post-down.sh
      volumes:
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-common-config
      - name: wg-config
        configMap:
          name: wg-config
          defaultMode: 0755
      hostNetwork: false
{{ end }}