{{ $replicaCount := index .Values "discordBotReplicaCount" }}
{{ if (ne .Values.werf.env "dev") }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-discord
  labels:
    app: {{ .Chart.Name }}-discord
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-discord
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-discord
    spec:
      containers:
      - name: {{ .Chart.Name }}-discord
        image: '{{ index .Values.werf.image "wfs-discord" }}'
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config
        volumeMounts:
        - name: config-files
          mountPath: /config
        # readinessProbe:
        #   httpGet:
        #     path: /api/healthz
        #     port: 3000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        #   failureThreshold: 3
        # livenessProbe:
        #   httpGet:
        #     path: /api/healthz
        #     port: 3000
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        #   failureThreshold: 3
      - name: wg-client
        image: globalartltd/wireguard:rc3
        securityContext:
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Moscow"
        volumeMounts:
        - name: wg-config
          mountPath: /etc/wireguard/wg0.conf
          subPath: wg-discord.conf
        - name: wg-config
          mountPath: /etc/wireguard/pre-up.sh
          subPath: wg-pre-up.sh
        - name: wg-config
          mountPath: /etc/wireguard/post-up.sh
          subPath: wg-post-up.sh
        - name: wg-config
          mountPath: /etc/wireguard/post-down.sh
          subPath: wg-post-down.sh
      volumes:
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-common-config
      - name: wg-config
        configMap:
          name: wg-config
          defaultMode: 0755
      hostNetwork: false
{{ end }}
