{{ $replicaCount := index .Values "discordBotReplicaCount" }}
{{ if (ne .Values.werf.env "dev") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-discord
  labels:
    app: {{ .Chart.Name }}-discord
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-discord
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-discord
    spec:
      containers:
      - name: {{ .Chart.Name }}-discord
        image: '{{ index .Values.werf.image "wfs-discord" }}'
        env:
          - name: http_proxy
            value: "{{.Values.proxyUrl}}"
          - name: https_proxy
            value: "{{.Values.proxyUrl}}"
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config
        # command: ["/bin/sh", "-c"]
        # args:
        #   - sleep infinity
        volumeMounts:
        - name: config-files
          mountPath: /config

      volumes:
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-common-config
{{ end }}
