{{ $replicaCount := index .Values "discordBotReplicaCount" }}
{{ if (ne .Values.werf.env "dev") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wg-config
data:
  wg0.conf: |
{{ .Values.wireguardConfig | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-discord
  labels:
    app: {{ .Chart.Name }}-discord
spec:
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-discord
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-discord
    spec:
      containers:
      - name: {{ .Chart.Name }}-discord
        image: '{{ index .Values.werf.image "wfs-discord" }}'
        envFrom:
        - configMapRef:
            name: {{ .Chart.Name }}-common-config
        volumeMounts:
        - name: config-files
          mountPath: /config
      - name: wg-client
        image: linuxserver/wireguard
        securityContext:
          privileged: true
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Moscow"
        volumeMounts:
        - name: wg-config
          mountPath: /config/wg0.conf
          subPath: wg0.conf
    
      volumes:
      - name: config-files
        configMap:
          name: {{ .Chart.Name }}-common-config
      - name: wg-config
        configMap:
          name: wg-config
      hostNetwork: false
{{ end }}
