export enum MissionEnum {
  SUNRISE = 'sunrise',
  PRIPYAT = 'pripyat',
  COLDPEAK = 'coldpeak',
  MARS = 'mars',
  BLACKOUT = 'blackout',
  ANUBIS = 'anubis',
  EARTH_SHAKER = 'earth_shaker',
  CYBER_HORDE = 'cyber_horde',
  ICEBREAKER = 'icebreaker',
  THE_HQ = 'the_hq',
  BLACK_SHARK = 'black_shark',
  SWARM = 'swarm',
  HYDRA = 'hydra',
  BLACKWOOD = 'blackwood',
  HEIST = 'heist',
  ENDOR = 'endorsurvival',
  MIDGARD = 'midgard',
  ASGARD = 'asgard',
}
