{{- $replicaCount := index .Values "replicaCount" -}}
{{- $redisHost := index .Values "redisHost" -}}
{{- $redisPort := index .Values "redisPort" -}}
{{- $redisStorageClass := index .Values "redisStorageClass" -}}
{{- $redisStorage := index .Values "redisStorage" -}}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $redisHost }}
  labels:
    app: {{ $redisHost }}
    app.kubernetes.io/component: {{ $redisHost }}
    app.kubernetes.io/instance: {{ $redisHost }}
spec:
  clusterIP: None
  ports:
  - port: {{ $redisPort }}
    targetPort: {{ $redisPort }}
    name: {{ $redisHost }}
  selector:
    app: {{ $redisHost }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $redisHost }}
spec:
  serviceName: {{ $redisHost }}
  replicas: {{ $replicaCount }}
  selector:
    matchLabels:
      app: {{ $redisHost }}
  template:
    metadata:
      labels:
        app: {{ $redisHost }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ $redisHost }}
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: config
        image: redis:latest
        envFrom:
        - configMapRef:
            name: redis-config-values
        command: [ "sh", "-c", "/scripts/redis_init.sh" ]
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis/
        - name: config
          mountPath: /tmp/redis/
        - name: init-script
          mountPath: /scripts/
      containers:
      - name: redis
        image: redis:latest
        command: ["redis-server"]
        args: ["/etc/redis/redis.conf"]
        ports:
        - containerPort: {{ $redisPort }}
          name: redis
        volumeMounts:
        - name: redis-persist-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/
      volumes:
      - name: redis-config
        emptyDir: {}
      - name: init-script
        configMap:
          name: redis-scripts-config-map
          defaultMode: 0777
          items:
          - key: redis_init.sh
            path: redis_init.sh
      - name: config
        configMap:
          name: redis-config-map
          items:
          - key: redis.conf
            path: redis.conf
  volumeClaimTemplates:
  - metadata:
      name: redis-persist-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ $redisStorage }}
      storageClassName: {{ $redisStorageClass }}