deployEnv: stage
replicaCount: 1
apiUrl: http://wfs-api.wfs-stage.svc.cluster.local/api
translatorUrl: http://translator-service-api.translator-stage.svc.cluster.local/api
apiHost: wfs.glbart.dev
remoteDictsBotUrl: https://translator.globalart.dev/api/public/translates?projectId=8
remoteDictsAchievementsUrl: https://translator.globalart.dev/api/public/translates?projectId=9
translatorBotProjectId: 8
translatorAchievementProjectId: 9
redisReplicaCount: 1
redisHost: wfs-redis
redisPort: 6379
redisSentinelHost: wfs-sentinel
redisSentinelPort: 26379
redisSentinelMasterName: mymaster
redisCacheDatabase: 1
microserviceRedisDatabase: 2
callsRedisDatabase: 3
inMemoryQueueRedisDatabase: 4
redisStorageClass: standard
redisStorage: 1Gi
